### PR TITLE
fixes #30

### LINKED ISSUE #30: Show emoji name when hovering the emojis
Basically what I put on the title. If you're going to implement the feature to add emoji straight to focused input bar, it'll be best to be able to see the emoji's name when hovering it on the list. At the moment, since I tend to forget the actual meaning of certain emojis, I simply click on it to see its name from its BBCode descriptor.

### PR DESCRIPTION
**Pull request by jackunion**
fixes #30

### CODE REVIEW

**Comment by johannhof** [comment]
Thanks a ton! :heart: The build system is using an ancient version of Node, which is probably making the tests fail, so it's very likely not your fault. Let's merge this! :shipit:

**Comment by jackunion** [comment]
You are welcome :)
It would be great if you could check #45 as well, I've left couple notes there.
By the way, is it okay if I send you an email?

**Comment by johannhof** [comment]
@jackunion sure, send ahead, that's why it's on my profile :)

**Comment by johannhof** [comment]
I'll take a look at #45

**Pull request merged**
