### PR TITLE
Add support for Pale Moon 27.1+

### PR DESCRIPTION
**Pull request by JustOff**
Based on [PMkit documentation draft v1.1](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md), tested with [Pale Moon 27.1.0beta](https://forum.palemoon.org/viewtopic.php?f=1&t=14455).

### CODE REVIEW

**Comment by johannhof** [comment]
Thanks! Do you require anything else, like a new release on AMO?

**Comment by JustOff** [comment]
Thank you for supporting Pale Moon! Yes, please. Although the signed version isn't required, it would be very handy to have binary package for easy installation.

**Comment by JustOff** [comment]
Sorry for disturbing you, but considering the future [end of support of legacy addons in Firefox](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) it would be nice if you be so kind to host current version of Emoji Cheatsheet at https://addons.palemoon.org (I can assist you in this if needed).

**Comment by ZdrowyGosciu** [comment]
+1

**Pull request merged**
